name: Deploy Streamlit Frontend to EC2

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=frontend
            -Dsonar.projectName=frontend
            -Dsonar.sources=frontend

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN }}
          aws-region: us-east-1   

      - name: Clone / Pull Repository
        run: |
         COMMAND_ID=$(aws ssm send-command \
         --instance-ids "${{ secrets.INSTANCE_ID }}" \
         --document-name "AWS-RunShellScript" \
         --parameters 'commands=[
         "APP_DIR=/home/ec2-user/front",
         "REPO_NAME=java_springboot_project",
         "REPO_URL=https://github.com/kashifsayyad09/java_springboot_project.git",
         "mkdir -p $APP_DIR",
         "cd $APP_DIR",
         "if [ -d \"$REPO_NAME/.git\" ]; then cd $REPO_NAME && git reset --hard && git pull origin main; else git clone $REPO_URL && cd $REPO_NAME; fi"
         ]' \
         --query "Command.CommandId" \
         --output text)

         aws ssm wait command-executed \
         --command-id $COMMAND_ID \
         --instance-id "${{ secrets.INSTANCE_ID }}"   

      - name: Install Python
        run: |    
         COMMAND_ID=$(aws ssm send-command \
         --instance-ids "${{ secrets.INSTANCE_ID }}" \
         --document-name AWS-RunShellScript \
         --parameters 'commands=[
         "sudo dnf install -y python3 python3-pip",
         "cd /home/ec2-user/front/java_springboot_project/frontend",
         "python3 -m venv venv || true"
         ]' \
         --query "Command.CommandId" \
         --output text)

         aws ssm wait command-executed \
         --command-id $COMMAND_ID \
         --instance-id "${{ secrets.INSTANCE_ID }}"

      - name: Install Python Packages
        run: |
         COMMAND_ID=$(aws ssm send-command \
         --instance-ids "${{ secrets.INSTANCE_ID }}" \
         --document-name AWS-RunShellScript \
         --parameters 'commands=[
         "cd /home/ec2-user/front/java_springboot_project/frontend",
         "source venv/bin/activate",
         "pip install --upgrade pip",
         "pip install -r requirements.txt"
         ]' \
         --query "Command.CommandId" \
         --output text)

         aws ssm wait command-executed \
         --command-id $COMMAND_ID \
         --instance-id "${{ secrets.INSTANCE_ID }}"          

      - name: Configure Frontend Service
        run: |
         COMMAND_ID=$(aws ssm send-command \
         --instance-ids "${{ secrets.INSTANCE_ID }}" \
         --document-name AWS-RunShellScript \
         --parameters 'commands=[
         "sudo tee /etc/systemd/system/frontend.service >/dev/null <<EOF
         [Unit]
         Description=Streamlit Frontend
         After=network.target

         [Service]
         User=ec2-user
         WorkingDirectory=/home/ec2-user/front/java_springboot_project/frontend
         ExecStart=/bin/bash -c '\''source /home/ec2-user/front/java_springboot_project/frontend/venv/bin/activate && streamlit run app.py --server.port=8501 --server.address=0.0.0.0'\''
         Environment=API_URL=http://localhost:8084
         Restart=always
         RestartSec=5

         [Install]
         WantedBy=multi-user.target
         EOF"
         ]' \
         --query "Command.CommandId" \
         --output text)

         aws ssm wait command-executed \
         --command-id $COMMAND_ID \
         --instance-id "${{ secrets.INSTANCE_ID }}"  


      - name: Stop Old Frontend
        run: |
          COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ secrets.INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
          "echo Stopping frontend service...",
          "sudo systemctl stop frontend || true",
          "sudo systemctl disable frontend || true",
          "pkill -f streamlit || true",
          "sleep 5"
          ]' \
          --query "Command.CommandId" \
          --output text)

          aws ssm wait command-executed \
          --command-id $COMMAND_ID \
          --instance-id "${{ secrets.INSTANCE_ID }}"   

      - name: Restart Frontend
        run: |
          COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ secrets.INSTANCE_ID }}" \
          --document-name AWS-RunShellScript \
          --parameters 'commands=[
          "sudo systemctl daemon-reload",
          "sudo systemctl enable frontend",
          "sudo systemctl restart frontend"
          ]' \
          --query "Command.CommandId" \
          --output text)

          aws ssm wait command-executed \
          --command-id $COMMAND_ID \
          --instance-id "${{ secrets.INSTANCE_ID }}"  

      - name: Verify Frontend
        run: |
         COMMAND_ID=$(aws ssm send-command \
         --instance-ids "${{ secrets.INSTANCE_ID }}" \
         --document-name AWS-RunShellScript \
         --parameters 'commands=[
         "sleep 15",
         "curl -I http://localhost:8501"
         ]' \
         --query "Command.CommandId" \
         --output text)

         aws ssm wait command-executed \
         --command-id $COMMAND_ID \
         --instance-id "${{ secrets.INSTANCE_ID }}"   

         
     
